name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [node, python, go]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        if: matrix.lang == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Node | install & test
        if: matrix.lang == 'node'
        run: |
          npm ci || npm i
          npm run lint || true
          npm test || true
          npm run build || true

      - name: Setup Python
        if: matrix.lang == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Python | install & test
        if: matrix.lang == 'python'
        run: |
          python -m pip install -U pip
          [ -f requirements.txt ] && pip install -r requirements.txt || true
          pip install ruff black pytest build || true
          ruff check . || true
          pytest -q || true
          python -m build || true

      - name: Setup Go
        if: matrix.lang == 'go'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Go | lint & test & build
        if: matrix.lang == 'go'
        run: |
          go test ./...
          go build ./...

  release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci || true
      - run: npx semantic-release || true
